# Generated by Django 5.1 on 2026-07-31 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbportal', '0002_category_jobtype_job_apply_job_category_job_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='apply',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jbportal.category'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jbportal.jobtype'),
        ),
    ]
