# Generated by Django 5.1 on 2026-07-31 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbportal', '0003_alter_job_apply_alter_job_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='apply',
        ),
        migrations.AddField(
            model_name='job',
            name='apply_link',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='apply_type',
            field=models.CharField(choices=[('resume', 'Resume'), ('link', 'Link')], default='resume', max_length=10),
        ),
    ]
