# Generated by Django 5.1 on 2026-07-31 12:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbportal', '0006_alter_job_added_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='job_views', to=settings.AUTH_USER_MODEL),
        ),
    ]
