# Generated by Django 5.1 on 2026-07-31 13:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbportal', '0007_job_views'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='apply_link_clicks',
            field=models.ManyToManyField(blank=True, related_name='apply_link_clicks', to=settings.AUTH_USER_MODEL),
        ),
    ]
