# Generated by Django 5.1 on 2026-08-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbportal', '0008_job_apply_link_clicks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='apply_link_clicks',
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
    ]
