# Generated by Django 5.1 on 2026-09-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbportal', '0009_remove_job_apply_link_clicks_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='apply_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
